//products
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const POST_PRODUCT = "POST_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SORT_BY_SCORE = "SORT_BY_SCORE";
export const SORT_BY_TIME_PREPARATION = "SORT_BY_TIME_PREPARATION";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const FILTER_BY_DIET = "FILTER_BY_DIET";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SORT_PRODUCTS_BY_PRICE = "SORT_PRODUCTS_BY_PRICE";
export const GET_PROFILE_BY_ID= "GET_PROFILE_BY_ID";
export const CREATE_PROFILE= "CREATE_PROFILE";
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const CLEAR_CART = "CLEAR_CART";
//Users

//Reservations
